feat: add projects in 24060122140104/
Praktikum-PBP-2024/Praktikum-05 pull request #7
Opened 2024-10-01 13:17 UTC by Alwey64Lover

2024-10-02 00:13 UTC, Reylyer commented on 24060122140104/lib/db_login.php
ganti dbhost dengan pbp.shariyl.cloud:3306


untuk revisi silahkan commit revisi terbaru lalu push. Jika sudah tinggalkan pesan sudah revisi disini

2024-10-02 00:14 UTC, Reylyer requested changes
Refisi db_login

2024-10-02 00:38 UTC, Alwey64Lover commented on 24060122140104/lib/db_login.php
sudah revisi

2024-10-03 09:35 UTC, Reylyer commented on 24060122140104/lib/db_login.php
keren

2024-10-03 09:35 UTC, Reylyer approved these changes
ok

2024-10-03 09:35 UTC, merged